# arxivの学問領域の指定
subject: 'cat:cs.AR OR cs.ET OR cs.NI'

# 検索キーワード
keywords:
        NoCs: 8
        Network-on-Chip: 8
        On-Chip Network: 8
        Many-Core: 5
        Cache: 2
        CMPs: 8
        Chip Multi-Processors: 8
        routing: 3
        topology: 3
        heterogeneous: 3
        Data center: 3
        Data centre: 3
        scalable: 1
        scalability: 1
        crossbar: 3
        traversal: 2
        circuit-switching: 3
        circuit-switched: 3
        flit: 5
        

# 通知の閾値
score_threshold: 8
